# Generated by Django 3.1.3 on 2021-01-08 16:06

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('payments', '0001_initial'),
        ('quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=secrets.token_urlsafe, max_length=50, unique=True)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('is_used', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('activation_datetime', models.DateTimeField(default=None, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.centurionproject')),
                ('quantum_charge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quantum.quantumcharge')),
            ],
        ),
    ]
