version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      centurion-net:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./centurion_crowdsale/ducx_tokens:/app/centurion_crowdsale/ducx_tokens
      - ./centurion_crowdsale/invest_requests:/app/centurion_crowdsale/invest_requests
      - ./centurion_crowdsale/payments:/app/centurion_crowdsale/payments
      - ./centurion_crowdsale/projects:/app/centurion_crowdsale/projects
      - ./centurion_crowdsale/quantum:/app/centurion_crowdsale/quantum
      - ./centurion_crowdsale/rates:/app/centurion_crowdsale/rates
      - ./centurion_crowdsale/transfers:/app/centurion_crowdsale/transfers
      - ./centurion_crowdsale/vouchers:/app/centurion_crowdsale/vouchers
    networks:
      centurion-net:
  receiver:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/receiver.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      centurion-net:
  rates_checker:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/rates_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      centurion-net:
  scanner:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/scanner.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      centurion-net:
    volumes:
      - ./mywill_scanner/settings:/app/mywill_scanner/settings
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      centurion-net:
  celery:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/celery.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      centurion-net:

networks:
  centurion-net:
