# Generated by Django 3.1.3 on 2021-01-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invest_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=78)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('invest_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invest_requests.investrequest')),
            ],
        ),
    ]
