# Generated by Django 3.1.3 on 2021-01-08 16:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ducx_tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenturionProject',
            fields=[
                ('string_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=50)),
                ('description_title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('default_image', models.CharField(max_length=50)),
                ('usd_target_raise', models.DecimalField(decimal_places=2, max_digits=100)),
                ('usd_collected_from_fiat', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('usd_collected_from_duc', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('duc_collected', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('usd_minimal_purchase', models.IntegerField()),
                ('raise_start_datetime', models.DateTimeField(default=None, null=True)),
                ('raise_months', models.IntegerField()),
                ('months_between_raise_and_staking', models.IntegerField()),
                ('duc_percent_in_target_raise', models.IntegerField()),
                ('ducx_staking_monthly_percent', models.IntegerField()),
                ('staking_months', models.IntegerField()),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ducx_tokens.ducxtoken')),
            ],
        ),
    ]
