# Generated by Django 3.1.3 on 2021-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.FloatField()),
                ('ETH', models.FloatField()),
                ('USDC', models.FloatField()),
                ('USDT', models.FloatField()),
                ('DUC', models.FloatField()),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
