# Generated by Django 3.1.3 on 2021-01-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('duc_address', models.CharField(max_length=50)),
                ('btc_address', models.CharField(max_length=50)),
                ('eth_address', models.CharField(max_length=50)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.centurionproject')),
            ],
        ),
    ]
